all: cf3 cf4 cf5 cf6

cf3: test8.o test3.o
	cc -framework CoreFoundation $+ -o $@

cf4: test8.o test4.o
	cc -framework CoreFoundation $+ -o $@

cf5: test8.o test5.o
	cc -framework CoreFoundation $+ -o $@

cf6: test8.o test6.o
	cc -framework CoreFoundation $+ -o $@
